### ISSUE TITLE
热力图显示问题

### ISSUE THREAD

**Issue by ybtsdst** [maptalks/maptalks.heatmap#38]
![Selection_082](https://user-images.githubusercontent.com/3139535/57284231-548e2680-70e3-11e9-95e1-1fe35a2eddd0.png)
![Selection_081](https://user-images.githubusercontent.com/3139535/57284232-5526bd00-70e3-11e9-93b5-a15eaa1fd531.png)
问下，我从openlayers换过来，发现热力图显示的不正常(默认参数)，颜色非常的淡
我看数据都没问题， 第一张图是数据。
是需要调整radius和blur这两个参数么？

**Comment by ybtsdst** [comment]
@fuzhenn 大佬方便的时候帮忙看下吧

**Comment by fuzhenn** [comment]
问题已经解决并发布新版本：
v0.6.0
